# Generated by Django 3.0.9 on 2020-08-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=30)),
                ('store_id', models.CharField(max_length=30)),
                ('elec_available', models.CharField(max_length=30)),
            ],
        ),
    ]
