# Generated by Django 2.1.15 on 2020-08-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_pic', models.CharField(blank=True, max_length=256, null=True)),
                ('mac_addr', models.CharField(blank=True, max_length=256, null=True)),
                ('cur_host', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=256, null=True)),
                ('store_location', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(blank=True, max_length=256, null=True)),
                ('pic_f_x', models.FloatField(blank=True, null=True)),
                ('pic_f_y', models.FloatField(blank=True, null=True)),
                ('pic_s_x', models.FloatField(blank=True, null=True)),
                ('pic_s_y', models.FloatField(blank=True, null=True)),
                ('layout_f_x', models.FloatField(blank=True, null=True)),
                ('layout_f_y', models.FloatField(blank=True, null=True)),
                ('layout_s_x', models.FloatField(blank=True, null=True)),
                ('layout_s_y', models.FloatField(blank=True, null=True)),
                ('is_elec', models.NullBooleanField(default=False)),
                ('capacity', models.IntegerField(default=-1)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watcher.Camera')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watcher.Store')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watcher.Store'),
        ),
    ]
