# Generated by Django 3.1 on 2020-08-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_elec',
            field=models.BooleanField(default=False),
        ),
    ]
