# Generated by Django 3.0.9 on 2020-08-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_auto_20200819_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
