# Generated by Django 3.0.9 on 2020-08-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0003_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(blank=True, max_length=256, null=True)),
                ('pic_f_x', models.FloatField(blank=True, null=True)),
                ('pic_f_y', models.FloatField(blank=True, null=True)),
                ('pic_s_x', models.FloatField(blank=True, null=True)),
                ('pic_s_y', models.FloatField(blank=True, null=True)),
                ('layout_f_x', models.FloatField(blank=True, null=True)),
                ('layout_f_y', models.FloatField(blank=True, null=True)),
                ('layout_s_x', models.FloatField(blank=True, null=True)),
                ('layout_s_y', models.FloatField(blank=True, null=True)),
                ('is_elec', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(default=-1)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watcher.Camera')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watcher.Store')),
            ],
        ),
    ]
