# Generated by Django 3.0.9 on 2020-08-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0004_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='description',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_location',
        ),
    ]
