# Generated by Django 3.1 on 2020-09-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0004_table_is_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='picture_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
