# Generated by Django 3.0.9 on 2020-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0005_auto_20200820_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
