# Generated by Django 3.1 on 2020-12-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0005_store_picture_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
